CREATE TABLE `customer_churn_raw` (
  `RowNumber` INT NULL,
  `CustomerId` INT NULL,
  `Surname` VARCHAR(50) NULL,
  `CreditScore` INT NULL,
  `Geography` VARCHAR(50) NULL,
  `Gender` VARCHAR(50) NULL,
  `Age` INT NULL,
  `Tenure` INT NULL,
  `Balance` DOUBLE NULL,
  `NumOfProducts` INT NULL,
  `HasCrCard` INT NULL,
  `IsActiveMember` INT NULL,
  `EstimatedSalary` DOUBLE NULL,
  `Exited` INT NULL,
  `Complain` INT NULL,
  `Satisfaction_Score` INT NULL,
  `Card_Type` VARCHAR(50) NULL,
  `Point_Earned` INT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;